name: QA
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '40 2 * * *'

jobs:
  tests:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        env:
          - PHP_IMAGE: php:8.2-cli
            COVERAGE_FILE: coverage.clover
          - PHP_IMAGE: php:8.3-cli
            QA: 1
          - PHP_IMAGE: php:8.4-cli
          - PHP_IMAGE: php:8.5-cli

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Build docker image
        env: ${{ matrix.env }}
        run: ./dockerfile.sh | docker build -t msgpack -

      - name: Test
        env: ${{ matrix.env }}
        run: docker run --rm -v $PWD:/msgpack -w /msgpack msgpack

      - name: Check code quality
        env: ${{ matrix.env }}
        if: ${{ env.QA }}
        run: |
          docker run --rm -v $PWD:/msgpack -w /msgpack msgpack php vendor/bin/php-cs-fixer fix --dry-run --diff --verbose .
          docker run --rm -v $PWD:/msgpack -w /msgpack msgpack php vendor/bin/psalm

      - name: Upload code coverage to Scrutinizer
        env: ${{ matrix.env }}
        if: ${{ env.COVERAGE_FILE }}
        run: |
          docker run --rm -e COVERAGE_FILE -v $PWD:/msgpack -w /msgpack msgpack sh -lc '
            composer global require --no-progress --no-interaction scrutinizer/ocular:^1.9 >/dev/null &&
            "$(composer global config bin-dir --absolute)/ocular" code-coverage:upload --format=php-clover "$COVERAGE_FILE"
          '
